
export const VIEW_ONLY ="VIEW_ONLY"
export const VIEW_SALARY_INCREASE = "VIEW_SALARY_INCREASE"
export const EDIT_SALARY_INCREASE = "EDIT_SALARY_INCREASE"
export const VIEW_PROCESS = "VIEW_PROCESS"
export const EDIT_PROCESS = "EDIT_PROCESS"
export const VIEW_PROPOSAL = "VIEW_PROPOSAL"
export const EDIT_PROPOSAL = "EDIT_PROPOSAL"
export const ACTION_SALARY_INCREASE = "ACTION_SALARY_INCREASE"
export const ACTION_PROCESS = "ACTION_PROCESS"
export const ACTION_PROPOSAL = "ACTION_PROPOSAL"
export const ACTION_END_EMPLOYEE = "ACTION_END_EMPLOYEE"
export const EDIT_END_EMPLOYEE = "EDIT_END_EMPLOYEE"

export const statusesForSubmitLeader = [EDIT_END_EMPLOYEE ,EDIT_SALARY_INCREASE,EDIT_PROCESS ,EDIT_PROPOSAL ]
export const statusesForLeaderAction = [ ACTION_END_EMPLOYEE,
    ACTION_SALARY_INCREASE,
    ACTION_PROPOSAL,
    ACTION_PROCESS,]
export const statusOpenFormSalary = [VIEW_SALARY_INCREASE,ACTION_SALARY_INCREASE,EDIT_SALARY_INCREASE]
export const statusOpenFormProcess = [VIEW_PROCESS,ACTION_PROCESS,EDIT_PROCESS]
export const statusOpenFormProposal = [VIEW_PROPOSAL,ACTION_PROPOSAL,EDIT_PROPOSAL]
export const statusOpenFormEnd = [ACTION_END_EMPLOYEE,EDIT_END_EMPLOYEE,VIEW_ONLY]