export const ALL_CERTIFICATE_BY_ID_REQUEST = "ALL_CERTIFICATE_BY_ID_REQUEST";
export const ALL_CERTIFICATE_BY_ID_SUCCESS = "ALL_CERTIFICATE_BY_ID_SUCCESS";
export const ALL_CERTIFICATE_BY_ID_FAIL = "ALL_CERTIFICATE_BY_ID_FAIL";

export const ADD_CERTIFICATE_REQUEST = "ADD_CERTIFICATE_REQUEST";
export const ADD_CERTIFICATE_SUCCESS = "ADD_CERTIFICATE_SUCCESS";
export const ADD_CERTIFICATE_FAIL = "ADD_CERTIFICATE_FAIL";

export const UPDATE_CERTIFICATE_REQUEST = "UPDATE_CERTIFICATE_REQUEST";
export const UPDATE_CERTIFICATE_SUCCESS = "UPDATE_CERTIFICATE_SUCCESS";
export const UPDATE_CERTIFICATE_FAIL = "UPDATE_CERTIFICATE_FAIL";

export const DELETE_CERTIFICATE_REQUEST = "DELETE_CERTIFICATE_REQUEST";
export const DELETE_CERTIFICATE_SUCCESS = "DELETE_CERTIFICATE_SUCCESS";
export const DELETE_CERTIFICATE_FAIL = "DELETE_CERTIFICATE_FAIL";

