export const ALL_FAMILY_BY_ID_REQUEST = "ALL_FAMILY_BY_ID_REQUEST";
export const ALL_FAMILY_BY_ID_SUCCESS = "ALL_FAMILY_BY_ID_SUCCESS";
export const ALL_FAMILY_BY_ID_FAIL = "ALL_FAMILY_BY_ID_FAIL";

export const ADD_FAMILY_REQUEST = "ADD_FAMILY_REQUEST";
export const ADD_FAMILY_SUCCESS = "ADD_FAMILY_SUCCESS";
export const ADD_FAMILY_FAIL = "ADD_FAMILY_FAIL";

export const UPDATE_FAMILY_REQUEST = "UPDATE_FAMILY_REQUEST";
export const UPDATE_FAMILY_SUCCESS = "UPDATE_FAMILY_SUCCESS";
export const UPDATE_FAMILY_FAIL = "UPDATE_FAMILY_FAIL";

export const DELETE_FAMILY_REQUEST = "DELETE_FAMILY_REQUEST";
export const DELETE_FAMILY_SUCCESS = "DELETE_FAMILY_SUCCESS";
export const DELETE_FAMILY_FAIL = "DELETE_FAMILY_FAIL";