export const ALL_LEADERS_REQUEST = "ALL_LEADERS_REQUEST";
export const ALL_LEADERS_SUCCESS = "ALL_LEADERS_SUCCESS";
export const ALL_LEADERS_FAIL = "ALL_LEADERS_FAIL";

export const GET_LEADERS_BY_ID_REQUEST = "GET_LEADERS_BY_ID_REQUEST";
export const GET_LEADERS_BY_ID_SUCCESS = "GET_LEADERS_BY_ID_SUCCESS";
export const GET_LEADERS_BY_ID_FAIL = "GET_LEADERS_BY_ID_FAIL";