export const GET_LIST_PENDING_PROCESS_REQUEST = "GET_LIST_PENDING_PROCESS_REQUEST";
export const GET_LIST_PENDING_PROCESS_SUCCESS = "GET_LIST_PENDING_PROCESS_SUCCESS";
export const GET_LIST_PENDING_PROCESS_FAIL = "GET_LIST_PENDING_PROCESS_FAIL";

export const GET_LIST_PROCESS_BY_EMPLOYEE_ID_REQUEST = "GET_LIST_PROCESS_BY_EMPLOYEE_ID_REQUEST";
export const GET_LIST_PROCESS_BY_EMPLOYEE_ID_SUCCESS = "GET_LIST_PROCESS_BY_EMPLOYEE_ID_SUCCESS";
export const GET_LIST_PROCESS_BY_EMPLOYEE_ID_FAIL = "GET_LIST_PROCESS_BY_EMPLOYEE_ID_FAIL";

export const CREATE_PROCESS_REQUEST = "CREATE_PROCESS_REQUEST";
export const CREATE_PROCESS_SUCCESS = "CREATE_PROCESS_SUCCESS";
export const CREATE_PROCESS_FAIL = "CREATE_PROCESS_FAIL";

export const DELETE_PROCESS_REQUEST = "DELETE_PROCESS_REQUEST";
export const DELETE_PROCESS_SUCCESS = "DELETE_PROCESS_SUCCESS";
export const DELETE_PROCESS_FAIL = "DELETE_PROCESS_FAIL";

export const UPDATE_PROCESS_REQUEST = "UPDATE_PROCESS_REQUEST";
export const UPDATE_PROCESS_SUCCESS = "UPDATE_PROCESS_SUCCESS";
export const UPDATE_PROCESS_FAIL = "UPDATE_PROCESS_FAIL";