export const GET_LIST_PENDING_PROPOSAL_REQUEST = "GET_LIST_PENDING_PROPOSAL_REQUEST";
export const GET_LIST_PENDING_PROPOSAL_SUCCESS = "GET_LIST_PENDING_PROPOSAL_SUCCESS";
export const GET_LIST_PENDING_PROPOSAL_FAIL = "GET_LIST_PENDING_PROPOSAL_FAIL";

export const GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_REQUEST = "GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_REQUEST";
export const GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_SUCCESS = "GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_SUCCESS";
export const GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_FAIL = "GET_LIST_PROPOSAL_BY_EMPLOYEE_ID_FAIL";

export const CREATE_PROPOSAL_REQUEST = "CREATE_PROPOSAL_REQUEST";
export const CREATE_PROPOSAL_SUCCESS = "CREATE_PROPOSAL_SUCCESS";
export const CREATE_PROPOSAL_FAIL = "CREATE_PROPOSAL_FAIL";

export const DELETE_PROPOSAL_REQUEST = "DELETE_PROPOSAL_REQUEST";
export const DELETE_PROPOSAL_SUCCESS = "DELETE_PROPOSAL_SUCCESS";
export const DELETE_PROPOSAL_FAIL = "DELETE_PROPOSAL_FAIL";

export const UPDATE_PROPOSAL_REQUEST = "UPDATE_PROPOSAL_REQUEST";
export const UPDATE_PROPOSAL_SUCCESS = "UPDATE_PROPOSAL_SUCCESS";
export const UPDATE_PROPOSAL_FAIL = "UPDATE_PROPOSAL_FAIL";