export const GET_LIST_PENDING_SALARY_INCREASE_REQUEST = "GET_LIST_PENDING_SALARY_INCREASE_REQUEST";
export const GET_LIST_PENDING_SALARY_INCREASE_SUCCESS = "GET_LIST_PENDING_SALARY_INCREASE_SUCCESS";
export const GET_LIST_PENDING_SALARY_INCREASE_FAIL = "GET_LIST_PENDING_SALARY_INCREASE_FAIL";

export const GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_REQUEST = "GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_REQUEST";
export const GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_SUCCESS = "GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_SUCCESS";
export const GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_FAIL = "GET_LIST_SALARY_INCREASE_BY_EMPLOYEE_ID_FAIL";

export const CREATE_SALARY_INCREASE_REQUEST = "CREATE_SALARY_INCREASE_REQUEST";
export const CREATE_SALARY_INCREASE_SUCCESS = "CREATE_SALARY_INCREASE_SUCCESS";
export const CREATE_SALARY_INCREASE_FAIL = "CREATE_SALARY_INCREASE_FAIL";

export const DELETE_SALARY_INCREASE_REQUEST = "DELETE_SALARY_INCREASE_REQUEST";
export const DELETE_SALARY_INCREASE_SUCCESS = "DELETE_SALARY_INCREASE_SUCCESS";
export const DELETE_SALARY_INCREASE_FAIL = "DELETE_SALARY_INCREASE_FAIL";

export const UPDATE_SALARY_INCREASE_REQUEST = "UPDATE_SALARY_INCREASE_REQUEST";
export const UPDATE_SALARY_INCREASE_SUCCESS = "UPDATE_SALARY_INCREASE_SUCCESS";
export const UPDATE_SALARY_INCREASE_FAIL = "UPDATE_SALARY_INCREASE_FAIL";